spring.application.name=desafio-design-patterns-bootcamp-santander-dio

# Chave gratuita em https://console.cloud.google.com/ (Books API)
google.books.api-key=${GOOGLE_BOOKS_API_KEY:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
