# Perfil de producao (Railway). Ative com SPRING_PROFILES_ACTIVE=prod

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

server.port=${PORT:8080}
